package com.analyticobjects.digitalsafe.ui;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 * A panel for listing stuff like search results.
 *
 * @author Joel Bondurant
 * @since 2013.09
 */
public class ListPanel extends javax.swing.JPanel {

	/**
	 * Creates new form ListPanel
	 */
	public ListPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listingTable = new javax.swing.JTable();

        listingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Listing"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(listingTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listingTable;
    // End of variables declaration//GEN-END:variables

	void setListing(List<String[]> listings) {
		this.listingTable.setModel(new ListingTableModel(listings));
	}

	private class ListingTableModel extends DefaultTableModel {

		ListingTableModel(List<String[]> listings) {
			super();
			this.addColumn("Listing");
			for (String[] fileListing : listings) {
				this.addRow(fileListing);
			}
		}
	}

}
